project:
  type: website
  render:
  - predictions.qmd
  - methodology.qmd
  - index.qmd

website:
  title: "BGG Models"
  navbar:
    left:
      - text: "Predictions"
        href: index.qmd
      - text: "Methodology"
        href: methodology.qmd
      - text: "Pipeline"
        href: predictions.qmd

    right: 
      - icon: github
        href: http://github.com/phenrickson/
      - icon: linkedin
        href: https://www.linkedin.com/in/phenrickson/


format:
  html:
    author: "Phil Henrickson"
    date: today
    toc: true
    number-sections: true
    message: false
    warning: false
    code-fold: true
    code-overflow: scroll
    code-summary: 'Show the code'
    embed-resources: false
    html-math-method: mathjax
    fig-align: center
    theme: cerulean
    page-layout: full
    html-table-processing: none
    include-in-header:
    - text: |
          <style>
          .panel-tabset > .nav-tabs,
          .panel-tabset > .tab-content {border: none;}
          </style>
css: styles.css
