---
title: "Untitled"
author: "Phil Henrickson"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny

---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = F)

```

# Upcoming Games

## Overall

### 2023

### 2024

### 2025

## Category

### Economic

### War

### Card

```{r}

gt_tbl = 
        games_predicted %>%
        filter(yearpublished == 2023) %>%
        make_outcome_predictions_gt_table(
                predictions =.,
                game_data = games,
                top_n = 25
        )

# predictions from linear models

library(gt)

games_predicted %>%
        filter(games)

games_predicted %>%
        filter(yearpublished == 2023) %>%
        make_outcome_predictions_gt_table(
                predictions =.,
                game_data = games,
                top_n = 25
        )

games_predicted %>%
        filter(yearpublished == 2024) %>%
        make_outcome_predictions_gt_table(
                predictions =.,
                game_data = games,
                top_n = 25
        )

games_predicted %>%
        filter(yearpublished == 2024) %>%
        filter(game_id %in% 
                       (
                               games %>% 
                                       select(game_id, name, categories) %>%
                                       unnest(categories)  %>%
                                       filter(value == 'Card Game') %>%
                                       pull(game_id)
                       )
        ) %>%
        make_outcome_predictions_gt_table(
                predictions =.,
                game_data = games,
        )
        gt::tab_header(
                title = paste("Top Games by Year for",
                              get_username()),
                subtitle = paste("Rankings based on predictive model trained on user's collection using games released through", user_output$end_train_year)
        )
        
        


```


##

```{r}

ui <- fluidPage(
        selectInput("yearpublished",
                    "Year:",
                    choices = c(2023, 2024, 2025)),
        gt_output(outputId = "table")
)

server <- function(input, output, session) {
        
        
        
        gt_tbl = reactive({
                
                         games_predicted %>%
                                  filter(yearpublished == input$yearpublished) %>%
                                  make_outcome_predictions_gt_table(
                                          predictions =.,
                                          game_data = games,
                                          top_n = 25)
        })
        output$table <- 
                render_gt(
                        expr = gt_tbl()
                )
                                  
        }

shinyApp(ui = ui, server = server)

```


```{r}

# not run
targets::tar_load_globals()

library(fastshap)
library(shapviz)

source(here::here("src", "reports", "outcome_reports.R"))

# load data
tar_load(games_processed)
tar_load(games_imputed)

# load models
model_average =
        vetiver::vetiver_pin_read(
                board = get_gcs_board('deployed'),
                name = "vetiver_average_"
        )

model_averageweight =
        vetiver::vetiver_pin_read(
                board = get_gcs_board('deployed'),
                name = "vetiver_averageweight_"
        )

model_usersrated =
        vetiver::vetiver_pin_read(
                board = get_gcs_board('deployed'),
                name = "vetiver_usersrated"
        )


explain_averageweight = 
        model_averageweight %>%
        extract_vetiver_workflow_objects()

explain_average = 
        model_average %>%
        extract_vetiver_workflow_objects()

explain_usersrated = 
        model_usersrated %>%
        extract_vetiver_workflow_objects()

explain_average %>%
        explain_prediction(
                games_imputed %>%
                        filter(name == 'Gloomhaven')
        ) %>%
        prep_plot_explain()

map2_df(.x = games_imputed %>%
                filter(!is.na(bayesaverage)) %>%
                filter(yearpublished == 2022) %>%
                sample_n(1) %>%
                pull(name),
        .y = list(explain_averageweight,
                  explain_average,
                  explain_usersrated),
        ~ .y %>%
                explain_prediction(
                        games_imputed %>%
                                filter(name == .x)
                ) %>%
                prep_plot_explain(top_n = 15)) %>%
        plot_explain() %>%
        add_plot_explain_title(width = 50)

explain_game


# explain_prediction_objects = 
#         explain_average %>%
#         explain_prediction(
#                 new_data = 
#                         games_imputed %>%
#                         sample_n(4)
#         )
# 
# plots = 
#         explain_prediction_objects %>%
#         prep_plot_explain(top_n = 15) %>%
#         split(~game_id) %>%
#         map( ~ .x %>% 
#                      plot_explain() %>%
#                      add_plot_explain_title(width = 40)+
#                      coord_cartesian(xlim = c(-0.75, 0.75))
#         )
# 
# gridExtra::grid.arrange(grobs = plots)


```

