name: render quarto

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        r-version: ['4.4.1']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          use-public-rspm: true
      - name: Install additional Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgit2-dev libglpk40 libmagick++-dev
          sudo apt install cmake libcurl4-openssl-dev libglpk-dev libnode-dev pandoc
      - name: Setup renv and install packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        env:
          RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/all/latest
          GITHUB_PAT: ${{ secrets.GH_PAT}}
      - name: Run targets
        run: |
            targets::tar_make()
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT}}
          GCS_AUTH_FILE: ${{ secrets.GCS_AUTH_FILE}}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          GCS_AUTH_FILE: ${{ secrets.GCS_AUTH_FILE }}